name: Docker Image Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-image:
    uses: team-telnyx/infra-ci-gha-workflows/.github/workflows/dockerImage.yml@main
    secrets: inherit